Errors from toThrow are easier to understand
It is difficult to see what went wrong when using `expect(fn).toThrow('expected message')` and the function either doesn’t throw or it throws and error that doesn't match the expected error message. Currently those two cases look exactly the same when the test fails.

This changes the assertion errors thrown from `toThrow` to show the reason why the assertion failed.

- The context object that is used as `this` when calling matchers now has a method named `setErrorProperties`. This method can be used to override the properties passed to `ExpectationError`. My initial plan was to just throw custom `ExpectationError`s from the `toThrow` matcher but that wouldn’t work if the assertion is reversed (`expect(fn).not.toThrow()`).
- Assert that the actual value is a function. This will throw even if the assertion is reversed because not passing a function is a programmer error. For example: `expect(‘x’).not.toThrow()` will now throw an error.
- Custom assertion message when the function does not throw. This should make it clear that the problem is not a mismatch of error messages.
- Custom assertion message when the error message does not match the expected string or regexp. The assertion message makes it clear that it’s a mismatch of error messages and the `actual` and `expected` messages are passed to `ExpectationError`.
- Add unit tests for `toThrow`.

Example assertion errors:

```js
expect(function() {}).toThrow(‘the_expected_message’);
```

```
ExpectationError: Expected function to throw
```

```js
expect(function() {
  throw new Error('the_actual_message');
}).toThrow('the_expected_message');
```

```
ExpectationError: Expected function to throw an error with a message that match the expected string
+ expected - actual

-the_actual_message
+the_expected_message
```